-- 코드를 입력하세요
-- SELECT USER_ID, PRODUCT_ID
-- FROM ONLINE_SALE
-- WHERE USER_ID IN (
--     SELECT USER_ID
--     FROM ONLINE_SALE
--     GROUP BY USER_ID, PRODUCT_ID
--     HAVING COUNT(*) > 1
-- )
-- GROUP BY USER_ID, PRODUCT_ID
-- ORDER BY USER_ID ASC, PRODUCT_ID DESC;

SELECT t.USER_ID, t.PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(*)
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING COUNT(*) > 1
) t
ORDER BY t.USER_ID ASC, t.PRODUCT_ID DESC;

